### ISSUE TITLE
gmapsfield breaks dumpdata command

### ISSUE THREAD

**Issue by jbekesi** [bocoup/django_gmapsfield#5]
Upon manage.py dumpdata, this error is displayed:

```
Error: Unable to serialize database: Manager isn't accessible via xxxx instances
```

--traceback points back to fields.py, line 9

(Django 1.2.3)

**Comment by tbranyen** [comment]
Interesting I'll look into this tonight and hopefully have a patch landed tomorrow morning.

**Comment by tbranyen** [comment]
Committed a fix to the repo.  Please pull down latest source and test.  it appears the issue was with value_to_string inside the custom field.
